version: "3"
services: 
  app:
    depends_on: 
      - mysql
    build: ./
    ports: 
      - "80:80"
    networks: 
      - "proxy"
    logging:
      options: 
        max-size: "10k"
  redis:
    image: redis
    ports: 
      - "6379:6379"
    networks: 
      - "proxy"
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes: 
      - ./CalendarsDB.sql:/docker-entrypoint-initdb.d/CalendarsDB.sql
    networks: 
      - "proxy"


networks: 
  proxy:
    driver: bridge


