CREATE schema Projects;
use Projects;
CREATE TABLE 用户
(
用户名 VARCHAR(10) NOT NULL PRIMARY KEY,
密码 VARCHAR(255)
);

CREATE TABLE 工程
(
工程代码 BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
工程名 VARCHAR(255) NOT NULL,
工程描述 VARCHAR(255),
创建者 VARCHAR(10) NOT NULL,
PRIMARY KEY(工程代码),
FOREIGN KEY(创建者) REFERENCES 用户(用户名)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE 任务
(
任务代码 BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
任务名 VARCHAR(255) NOT NULL,
任务描述 VARCHAR(255),
创建者 VARCHAR(10) NOT NULL,
截止时间 DATETIME NOT NULL,
所属工程代码 BIGINT UNSIGNED NOT NULL,
PRIMARY KEY(任务代码),
FOREIGN KEY(所属工程代码) REFERENCES 工程(工程代码)
ON UPDATE CASCADE
ON DELETE CASCADE,
FOREIGN KEY(创建者) REFERENCES 用户(用户名)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE 用户_任务
(
执行者 VARCHAR(10) NOT NULL,
任务代码 BIGINT UNSIGNED NOT NULL,
所属工程代码 BIGINT UNSIGNED NOT NULL,
备注 VARCHAR(255),
PRIMARY KEY(执行者,任务代码),
FOREIGN KEY(执行者)REFERENCES 用户(用户名)
ON DELETE RESTRICT
ON UPDATE CASCADE,
FOREIGN KEY(任务代码) REFERENCES 任务(任务代码)
ON UPDATE CASCADE
ON DELETE CASCADE,
FOREIGN KEY(所属工程代码) REFERENCES 工程(工程代码)
ON UPDATE CASCADE
ON DELETE CASCADE
);